version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./Docker
      dockerfile: php.Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=PHPSTORM
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
